{
 "title": "Tendermint RPC Information",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block Latest Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_latest_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Latest Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_latest_block_time * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Latest Time Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - tendermint_latest_block_time",
     "legendFormat": "diff from now"
    },
    {
     "expr": "tendermint_latest_block_time_diff",
     "legendFormat": "diff from scrape"
    }
   ]
  }
 ]
}